### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by ghost** [noneymous/iota-miner#2]
I have this on fedora 27 : 

```
# python3 run.py 
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    import iota
  File "/root/iota-miner/iota/__init__.py", line 39, in <module>
    from .api import *
  File "/root/iota-miner/iota/api.py", line 10, in <module>
    from iota.commands import BaseCommand, CustomCommand, core, \
  File "/root/iota-miner/iota/commands/__init__.py", line 13, in <module>
    import filters as f
ImportError: No module named 'filters'
```

**Comment by noneymous** [comment]
You are missing a dependency

#> pip install filters

or 

#> pip3 install filters
